name: Test Donut Falls raven assembly from directory

on: [pull_request, workflow_dispatch]

jobs:

  test:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          lfs: true

      - name: Checkout LFS objects
        run: git lfs checkout
            
      - name: Install Nextflow
        run: |
          wget -qO- get.nextflow.io | bash
          sudo mv nextflow /usr/local/bin/
          
      - name: Run Donut Falls
        run: |
          docker --version

          mkdir reads
          
          wget -q https://github.com/nf-core/test-datasets/blob/23f5b889e4736798c8692e9b92810d9a3e37ee97/nanopore/subset15000.fq.gz?raw=true -O reads/nfcore_subset15000.fa.gz

          wget -q https://bridges.monash.edu/ndownloader/files/23754659 -O great_dataset.tar.gz
          tar -xvf great_dataset.tar.gz
          mv reads.fastq.gz reads/.
          
          nextflow run . -profile docker -c .github/workflows/github_actions.config --reads reads --assembler raven

          tree donut_falls